### ISSUE TITLE
In Extractors.pyx: TypeError:long()

### ISSUE THREAD

**Issue by veerarc** [attardi/deepnl#21]
I have been trying to train dl-ner.py on a new dataset. Could you kindly help me in tracing the error log shown below:

Generated 215 feature vectors with 100 features each.
Overriding vocabulary in deepnl_parameters/vocab
Creating capitalization features...
Generated 5 feature vectors with 5 features each.
Loading suffix list...
Generated 74 feature vectors with 5 features each.
Loading prefix list...
Generated 200 feature vectors with 5 features each.
Loading gazetteers
Generated 3 feature vectors with 5 features each.
Traceback (most recent call last):
  File "../bin/dl-ner.py", line 358, in <module>
    main()
  File "../bin/dl-ner.py", line 325, in main
    sentences.append(converter.convert(sent))
  File "deepnl/extractors.pyx", line 126, in deepnl.extractors.Converter.convert (deepnl/extractors.cpp:4571)
  File "deepnl/extractors.pyx", line 132, in deepnl.extractors.Converter.convert (deepnl/extractors.cpp:4489)
TypeError: long() argument must be a string or a number, not 'NoneType'

**Comment by attardi** [comment]
Check that your input is in the proper CoNLL format.
