### ISSUE TITLE
dl-words.py

### ISSUE THREAD

**Issue by maulikdang** [attardi/deepnl#30]
Hi, I am trying to execute the dl-words.py file but am facing the error given below.

Creating new network...
... with the following parameters:

```
    Input layer size: 56
    Hidden layer size: 200
    Output size: 1
```

Starting training
Estimating max number of pairs
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "deepnl/words.pyx", line 248, in deepnl.words.LmTrainer.train.train_worker (deepnl/words.cpp:5112)
  File "deepnl/words.pyx", line 443, in deepnl.words.LmWorker.__init** (deepnl/words.cpp:8889)
  File "deepnl/words.pyx", line 118, in deepnl.words.LmTrainer.**init** (deepnl/words.cpp:3993)
TypeError: **init**() takes exactly 3 positional arguments (7 given)

**Comment by attardi** [comment]
It should be fixed, please try it.

**Comment by maulikdang** [comment]
Issue was fixed by using a large tsv file having many tweets.
