### ISSUE TITLE
deepnl ner error - SuffixExtractor has no attribute create

### ISSUE THREAD

**Issue by kiran-surya** [attardi/deepnl#4]
Hi @attardi,

I'm facing following issue while training deepnl for ner.

Traceback (most recent call last):
  File "bin/dl-ner.py", line 330, in <module>
    main()
  File "bin/dl-ner.py", line 258, in main
    extractor = SuffixExtractor.create(args.suffix, args.suffixes)
AttributeError: type object 'deepnl.extractors.SuffixExtractor' has no attribute 'create'

**Comment by kiran-surya** [comment]
With out suffixes option, i'm getting following error:

Generated 5500 feature vectors with 50 features each.
Overriding vocabulary in /home/ec2-user/data/vocab.txt
Creating capitalization features...
Generated 5 feature vectors with 5 features each.
Loading gazetteers
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Creating new network...
Traceback (most recent call last):
  File "bin/dl-ner.py", line 333, in <module>
    main()
  File "bin/dl-ner.py", line 310, in main
    trainer = create_trainer(args, converter, tag_index)
  File "bin/dl-ner.py", line 55, in create_trainer
    nn = SequenceNetwork(input_size, args.hidden, len(tag_index))
NameError: global name 'SequenceNetwork' is not defined

**Comment by attardi** [comment]
I will check the problem shortly.
Thank you for your patience.

##

**Comment by kiran-surya** [comment]
Thank you.

**Comment by attardi** [comment]
On 8/20/2015 09:10, kiran-surya wrote:

> Hi @attardi https://github.com/attardi,
> 
> I'm facing following issue while training deepnl for ner.
> 
> Traceback (most recent call last):
> File "bin/dl-ner.py", line 330, in
> main()
> File "bin/dl-ner.py", line 258, in main
> extractor = SuffixExtractor.create(args.suffix, args.suffixes)
> AttributeError: type object 'deepnl.extractors.SuffixExtractor' has no 
> attribute 'create'
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/attardi/deepnl/issues/4.
> 
> For a quick fix, replace SuffixExtractor.create with just SuffixExtractor.

##

**Comment by kiran-surya** [comment]
Thank you. what about second issue ?
Generated 5500 feature vectors with 50 features each.
Overriding vocabulary in /home/ec2-user/data/vocab.txt
Creating capitalization features...
Generated 5 feature vectors with 5 features each.
Loading gazetteers
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Creating new network...
Traceback (most recent call last):
File "bin/dl-ner.py", line 333, in 
main()
File "bin/dl-ner.py", line 310, in main
trainer = create_trainer(args, converter, tag_index)
File "bin/dl-ner.py", line 55, in create_trainer
nn = SequenceNetwork(input_size, args.hidden, len(tag_index))
NameError: global name 'SequenceNetwork' is not defined

**Comment by attardi** [comment]
Fixed in version 1.3.3.

**Comment by kiran-surya** [comment]
Facing this issue with latest code.

Creating new network...
... with the following parameters:

```
    Input layer size: 400
    Hidden layer size: 300
    Output size: 17
```

Starting training with 22138 sentences
Training for up to 40 epochs
Traceback (most recent call last):
  File "bin/dl-ner.py", line 331, in <module>
    main()
  File "bin/dl-ner.py", line 314, in main
    args.threads)
  File "deepnl/trainer.pyx", line 123, in deepnl.trainer.Trainer.train (deepnl/trainer.cpp:3526)
    self._train_epoch(examples, outcomes)
  File "deepnl/trainer.pyx", line 341, in deepnl.trainer.TaggerTrainer._train_epoch (deepnl/trainer.cpp:8359)
    scores = self.tagger._tag_sequence(sent, True)
  File "deepnl/tagger.pyx", line 72, in deepnl.tagger.Tagger._tag_sequence (deepnl/tagger.cpp:3605)
    cpdef np.ndarray[FLOAT_t,ndim=2] _tag_sequence(self,
  File "deepnl/tagger.pyx", line 124, in deepnl.tagger.Tagger._tag_sequence (deepnl/tagger.cpp:3439)
    nn.forward(vars)
  File "deepnl/network.pyx", line 210, in deepnl.network.Network.forward (deepnl/network.cpp:6406)
    cpdef forward(self, Variables vars):
  File "deepnl/network.pyx", line 215, in deepnl.network.Network.forward (deepnl/network.cpp:6255)
    self.p.hidden_weights.dot(vars.input, vars.hidden)
TypeError: function takes exactly 1 argument (2 given)

**Comment by attardi** [comment]
Your need numpy version 1.9.
I updated the requirements in setup.py.
