### ISSUE TITLE
Problem while giving Test data

### ISSUE THREAD

**Issue by prakhar987** [attardi/deepnl#42]
Hi,
I have trained a model successfully. But when I try passing a test file as : python2.7 dl-pos.py pos.dnn < test_records.tsv 
I get the following error : 
Traceback (most recent call last):
  File "dl-pos.py", line 338, in <module>
    main()
  File "dl-pos.py", line 324, in main
    print("Sent=",tagger.tag(sent))
  File "deepnl/tagger.pyx", line 50, in deepnl.tagger.Tagger.tag (deepnl/tagger.cpp:3170)
  File "deepnl/tagger.pyx", line 60, in deepnl.tagger.Tagger.tag (deepnl/tagger.cpp:2863)
  File "deepnl/extractors.pyx", line 132, in deepnl.extractors.Converter.convert (deepnl/extractors.cpp:4799)
  File "deepnl/extractors.pyx", line 263, in deepnl.extractors.Extractor.extract (deepnl/extractors.cpp:8305)
  File "build/bdist.linux-x86_64/egg/deepnl/word_dictionary.py", line 209, in __getitem__
TypeError: unhashable type: 'list'

**Comment by attardi** [comment]
Check your input.
Are you supplying a properly formatted tsv file?
