### ISSUE TITLE
unable to install deepnl in windows

### ISSUE THREAD

**Issue by tweetsharp** [attardi/deepnl#43]
hi
i want install deepnl in windows 10 x64. when i excute "python setup.py install" i get follow error :
plus i have problem to install some dependencies like Eigen.
any Idea?
```
C:\Users\regularman>python setup.py install
Please put "# distutils: language=c++" in your .pyx or .pxd file(s)
Traceback (most recent call last):
  File "C:\Users\regularman\Desktop\New Folder (4)\deepnl-master\setup.py", line 62, in <module>
    nthreads=4),
  File "C:\Users\regularman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\Cython\Build\Dependencies.py", line 818, in cythonize
    aliases=aliases)
  File "C:\Users\regularman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\Cython\Build\Dependencies.py", line 704, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "C:\Users\regularman\AppData\Local\Programs\Python\Python35-32\lib\site-packages\Cython\Build\Dependencies.py", line 108, in nonempty
    raise ValueError(error_msg)
ValueError: 'deepnl/words.pyx' doesn't match any files
```

**Comment by attardi** [comment]
Unfortunately not. I never tried DeepNL on Windows.
The error on missing file deepnl/words.pyx is strange.
On MacOs there was a problem with upper case in file names, but it was fixed.
