### ISSUE TITLE
'<' not supported between instances of 'dict' and 'dict'

### ISSUE THREAD

**Issue by alicjanna** [attardi/deepnl#54]
I'm trying to install the library on windows 10 on Anaconda 3 and I get the error. I run the command: python setup.py build   and I get this:

Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    nthreads=4),
  File "C:\Users\DominikaSarkowicz\Anaconda3\envs\tensorflow\lib\site-packages\Cython\Build\Dependencies.py", line 1000, in cythonize
    to_compile.sort()
TypeError: '<' not supported between instances of 'dict' and 'dict'

**Comment by Masum06** [comment]
@alicjanna Did you find a solution?

**Comment by akbir** [comment]
hey, i found you need to use python2 for this code to work. 
You also need to have Cython 2.5 installed. Any later version has a problem!

**Comment by alicjanna** [comment]
@am-khan Thanks for your answer.

**Comment by Masum06** [comment]
Thanks @am-khan !

**Comment by zhizhunbao** [comment]
Thanks @am-khan !

**Comment by 1eclipse** [comment]
Halo! Have you successfully installed deepnl? Where do you install it? windows, linux or mac?
i have some problems in windows? Can you help me?

**Comment by datdinhquoc** [comment]
not about deepnl, but i made it work this way

change
```
to_compile.sort()
```

to
```
to_compile.sort(key=lambda x: x[0]) # it's a tuple, the first value is numeric
```
