### ISSUE TITLE
Error while installation [cython compile error]

### ISSUE THREAD

**Issue by bakszero** [attardi/deepnl#58]
I get the following error while buildiing via 
`python setup.py build`

`deepnl/hpca.pyx:1:0: 'deepnl/hpca' is not a valid module name
Traceback (most recent call last):
  File "/home/baks/GSOC/ENV/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1164, in cythonize_one_helper
    return cythonize_one(*m)
  File "/home/baks/GSOC/ENV/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
CompileError: deepnl/hpca.pyx
[ 5/14] Cythonizing deepnl/network.pyx
Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    nthreads=4),
  File "/home/baks/GSOC/ENV/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1017, in cythonize
    result.get(99999)  # seconds
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
Cython.Compiler.Errors.CompileError: deepnl/hpca.pyx
`

**Comment by voluntadpear** [comment]
I'm having this same issue. Did you find a solution @bakszero?

**Comment by akanshajainn** [comment]
Did anyone solve it ? I am facing the same.

```
Please put "# distutils: language=c++" in your .pyx or .pxd file(s)
Compiling deepnl/hpca.pyx because it changed.
Compiling deepnl/classifier.pyx because it depends on ./deepnl/network.pxd.
Compiling deepnl/extractors.pyx because it depends on ./deepnl/network.pxd.
Compiling deepnl/hpca.pyx because it changed.
Compiling deepnl/sentiwords.pyx because it depends on ./deepnl/words.pxd.
[1/5] Cythonizing deepnl/hpca.pyx
[2/5] Cythonizing deepnl/hpca.pyx
[3/5] Cythonizing deepnl/classifier.pyx
[4/5] Cythonizing deepnl/sentiwords.pyx

Error compiling Cython file:
------------------------------------------------------------
...
# -*- coding: utf-8 -*-
^
------------------------------------------------------------

deepnl/hpca.pyx:1:0: 'deepnl/hpca' is not a valid module name
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1164, in cythonize_one_helper
    return cythonize_one(*m)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
CompileError: deepnl/hpca.pyx
[5/5] Cythonizing deepnl/extractors.pyx
Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    nthreads=4),
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 1017, in cythonize
    result.get(99999)  # seconds
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
Cython.Compiler.Errors.CompileError: deepnl/hpca.pyx
```

**Comment by shrebox** [comment]
I am facing the same issue. Did anyone get the solution?

**Comment by attardi** [comment]
The compiled  C++ code is already present in the distribution.
Issue a touch on the cpp files to reset their date:

touch deepnl/*.cpp

**Comment by shrebox** [comment]
> The compiled C++ code is already present in the distribution.
> Issue a touch on the cpp files to reset their date:
> 
> touch deepnl/*.cpp

Thanks a lot..it worked! :)

**Comment by sqsssq** [comment]
Where can I touch it?

**Comment by sqsssq** [comment]
> The compiled C++ code is already present in the distribution.
> Issue a touch on the cpp files to reset their date:
> 
> touch deepnl/*.cpp
![image](https://user-images.githubusercontent.com/44493311/60553538-46b4f480-9d66-11e9-8990-d7ed17ee962c.png)
I cannot find the correct address.

**Comment by bakszero** [comment]
> > The compiled C++ code is already present in the distribution.
> > Issue a touch on the cpp files to reset their date:
> > touch deepnl/*.cpp
> > ![image](https://user-images.githubusercontent.com/44493311/60553538-46b4f480-9d66-11e9-8990-d7ed17ee962c.png)
> > I cannot find the correct address.

Well the `touch` command here refers to the UNIX version of it, you're probably running a node.js specific version on your Windows command prompt. Use GitBash terminal or MobaXterm for your system.

@attardi  Thanks, this works!

**Comment by sqsssq** [comment]
> Well the `touch` command here refers to the UNIX version of it, you're probably running a node.js specific version on your Windows command prompt. Use GitBash terminal or MobaXterm for your system.

Sorry， I cannot use unix.Can I use Windows to handle this problem?Thank you!
