### ISSUE TITLE
FloatingPointError: underflow encountered in multiply

### ISSUE THREAD

**Issue by kiran-surya** [attardi/deepnl#7]
File "bin/dl-ner.py", line 342, in <module>
    main()
  File "bin/dl-ner.py", line 325, in main
    args.threads)
  File "deepnl/trainer.pyx", line 126, in deepnl.trainer.Trainer.train (deepnl/trainer.cpp:3737)
    self._train_epoch(examples, outcomes)
  File "deepnl/trainer.pyx", line 340, in deepnl.trainer.TaggerTrainer._train_epoch (deepnl/trainer.cpp:8557)
    self.update(grads, self.learning_rate, sent, ada)
  File "deepnl/trainer.pyx", line 404, in deepnl.trainer.TaggerTrainer.update (deepnl/trainer.cpp:9623)
    self.nn.update(grads, learning_rate, ada)
  File "deepnl/network.pyx", line 295, in deepnl.network.Network.update (deepnl/network.cpp:7077)
    self.p.update(grads, learning_rate, ada)
  File "deepnl/networkseq.pyx", line 48, in deepnl.networkseq.SeqParameters.update (deepnl/networkseq.cpp:3130)
    super(SeqParameters, self).update(grads, learning_rate, ada)
  File "deepnl/network.pyx", line 80, in deepnl.network.Parameters.update (deepnl/network.cpp:4271)
    cpdef update(self, Gradients grads, float learning_rate,
  File "deepnl/network.pyx", line 96, in deepnl.network.Parameters.update (deepnl/network.cpp:3772)
    ada.addSquare(grads)
  File "deepnl/networkseq.pyx", line 111, in deepnl.networkseq.SeqGradients.addSquare (deepnl/networkseq.cpp:4540)
    self.transitions += grads.transitions \* grads.transitions
FloatingPointError: underflow encountered in multiply

**Comment by kiran-surya** [comment]
Hi @attardi 

Is there any stable version on which i can train the model

**Comment by attardi** [comment]
As far as I know, the latest version 1.3.8 is fairly stable.
I have tested with the SENNA embeddings in several configurations.
An underflow may occur due to the data and settings.
You can play with options like the learning rate, e.g:
   -l 0.0003
I also got best results by disabling the AdaGrad update algorithm using:
   --eps 0

**Comment by kiran-surya** [comment]
I'm facing this issue now:
reating capitalization features...
Generated 5 feature vectors with 5 features each.
Loading suffix list...
Generated 457 feature vectors with 5 features each.
Loading gazetteers
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Generated 3 feature vectors with 5 features each.
Creating new network...
... with the following parameters:

```
    Input layer size: 400
    Hidden layer size: 300
    Output size: 17
```

Starting training with 286490 sentences
Training for up to 1 epochs
Traceback (most recent call last):
  File "bin/dl-ner.py", line 342, in <module>
    main()
  File "bin/dl-ner.py", line 325, in main
    args.threads)
  File "deepnl/trainer.pyx", line 126, in deepnl.trainer.Trainer.train (deepnl/trainer.cpp:3737)
    self._train_epoch(examples, outcomes)
  File "deepnl/trainer.pyx", line 340, in deepnl.trainer.TaggerTrainer._train_epoch (deepnl/trainer.cpp:8557)
    self.update(grads, self.learning_rate, sent, ada)
  File "deepnl/trainer.pyx", line 404, in deepnl.trainer.TaggerTrainer.update (deepnl/trainer.cpp:9623)
    self.nn.update(grads, learning_rate, ada)
  File "deepnl/network.pyx", line 295, in deepnl.network.Network.update (deepnl/network.cpp:7077)
    self.p.update(grads, learning_rate, ada)
  File "deepnl/networkseq.pyx", line 48, in deepnl.networkseq.SeqParameters.update (deepnl/networkseq.cpp:3130)
    super(SeqParameters, self).update(grads, learning_rate, ada)
  File "deepnl/network.pyx", line 80, in deepnl.network.Parameters.update (deepnl/network.cpp:4271)
    cpdef update(self, Gradients grads, float learning_rate,
  File "deepnl/network.pyx", line 99, in deepnl.network.Parameters.update (deepnl/network.cpp:3960)
    self.hidden_weights += learning_rate \* grads.hidden_weights / np.sqrt(ada.hidden_weights + adaEps)
FloatingPointError: invalid value encountered in divide

**Comment by kiran-surya** [comment]
eps 0 making denominator 0 ???

**Comment by attardi** [comment]
eps 0 just disables AdaGrad.

**Comment by kiran-surya** [comment]
Training for up to 40 epochs
Traceback (most recent call last):
  File "bin/dl-ner.py", line 346, in <module>
    main()
  File "bin/dl-ner.py", line 325, in main
    args.threads)
  File "deepnl/trainer.pyx", line 126, in deepnl.trainer.Trainer.train (deepnl/trainer.cpp:3737)
    self._train_epoch(examples, outcomes)
  File "deepnl/trainer.pyx", line 340, in deepnl.trainer.TaggerTrainer._train_epoch (deepnl/trainer.cpp:8557)
    self.update(grads, self.learning_rate, sent, ada)
  File "deepnl/trainer.pyx", line 404, in deepnl.trainer.TaggerTrainer.update (deepnl/trainer.cpp:9623)
    self.nn.update(grads, learning_rate, ada)
  File "deepnl/network.pyx", line 295, in deepnl.network.Network.update (deepnl/network.cpp:7077)
    self.p.update(grads, learning_rate, ada)
  File "deepnl/networkseq.pyx", line 48, in deepnl.networkseq.SeqParameters.update (deepnl/networkseq.cpp:3130)
    super(SeqParameters, self).update(grads, learning_rate, ada)
  File "deepnl/network.pyx", line 80, in deepnl.network.Parameters.update (deepnl/network.cpp:4271)
    cpdef update(self, Gradients grads, float learning_rate,
  File "deepnl/network.pyx", line 99, in deepnl.network.Parameters.update (deepnl/network.cpp:3960)
    self.hidden_weights += learning_rate \* grads.hidden_weights / np.sqrt(ada.hidden_weights + adaEps)
FloatingPointError: invalid value encountered in divide

I'm facing this issue with eps 0.

**Comment by attardi** [comment]
You must be using an old version.
In the latest one, eps = 0 disables AdaGrad.

—
